#!/usr/bin/env bash
# llama-env.sh — Environment defaults for llama-aliases

LLM_MODELS_DIR="${LLM_MODELS_DIR:-$HOME/.llama/llama-models}"
LLM_DEFAULT_CTX="${LLM_DEFAULT_CTX:-196608}"
LLM_DEFAULT_GPU_LAYERS="${LLM_DEFAULT_GPU_LAYERS:-99}"
LLM_SERVER_HOST="${LLM_SERVER_HOST:-127.0.0.1}"
LLM_SERVER_PORT="${LLM_SERVER_PORT:-11434}"
LLM_HF_DEFAULT_USER="${LLM_HF_DEFAULT_USER:-unsloth}"
LLM_DEFAULT_CACHE_TYPE_K="${LLM_DEFAULT_CACHE_TYPE_K:-q8_0}"
LLM_DEFAULT_CACHE_TYPE_V="${LLM_DEFAULT_CACHE_TYPE_V:-q8_0}"
LLM_RUNTIME_CONFIG_FILE="${LLM_RUNTIME_CONFIG_FILE:-$HOME/.llama/llama-runtime.env}"
_LLAMA_MODEL_INDEX_FILE="${_LLAMA_MODEL_INDEX_FILE:-$HOME/.llama/llama-models/.index.json}"
LLM_DEFAULT_THREADS="${LLM_DEFAULT_THREADS:-}"
LLM_PIPE_N_PREDICT="${LLM_PIPE_N_PREDICT:-4096}"
LLM_NO_THINKING="${LLM_NO_THINKING:-0}"

_LLAMA_MTP_DRAFT_N_MAX="${_LLAMA_MTP_DRAFT_N_MAX:-2}"
_LLAMA_MLX_CHAT_MODULE="${_LLAMA_MLX_CHAT_MODULE:-mlx_vlm.chat}"

if [[ -n "$LLM_RUNTIME_CONFIG_FILE" && -f "$LLM_RUNTIME_CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$LLM_RUNTIME_CONFIG_FILE"
fi
