#!/usr/bin/env bash
# llama-config.sh — Runtime config get/set/save/load

_llama_config() {
    local key="$1"
    local value="$2"

    case "$key" in
        show|""|-h|--help)
            echo ""
            echo "llama config"
            echo "  LLM_DEFAULT_CTX=$LLM_DEFAULT_CTX"
            echo "  LLM_DEFAULT_CACHE_TYPE_K=$LLM_DEFAULT_CACHE_TYPE_K"
            echo "  LLM_DEFAULT_CACHE_TYPE_V=$LLM_DEFAULT_CACHE_TYPE_V"
            echo "  LLM_DEFAULT_THREADS=${LLM_DEFAULT_THREADS:-<auto p-cores>}"
            echo "  LLM_PIPE_N_PREDICT=$LLM_PIPE_N_PREDICT"
            echo "  LLM_NO_THINKING=$LLM_NO_THINKING"
            echo ""
            echo "Usage:"
            echo "  llama config LLM_DEFAULT_CTX <n>"
            echo "  llama config ctx <n>"
            echo "  llama config threads <n|auto>"
            echo "  llama config cache <type>"
            echo "  llama config pipe-n <n>"
            echo "  llama config no-thinking <on|off>"
            echo "  llama config save [file]"
            echo "  llama config load [file]"
            echo ""
            ;;
        ctx|LLM_DEFAULT_CTX)
            if [[ "$value" =~ ^[0-9]+$ ]]; then
                export LLM_DEFAULT_CTX="$value"
                echo "✓ LLM_DEFAULT_CTX=$LLM_DEFAULT_CTX"
            else
                echo "Usage: llama config LLM_DEFAULT_CTX <n>"
                return 1
            fi
            ;;
        threads)
            if [[ "$value" == "auto" || -z "$value" ]]; then
                export LLM_DEFAULT_THREADS=""
                echo "✓ LLM_DEFAULT_THREADS=<auto p-cores>"
            elif [[ "$value" =~ ^[0-9]+$ ]]; then
                export LLM_DEFAULT_THREADS="$value"
                echo "✓ LLM_DEFAULT_THREADS=$LLM_DEFAULT_THREADS"
            else
                echo "Usage: llama config threads <n|auto>"
                return 1
            fi
            ;;
        cache)
            [ -z "$value" ] && { echo "Usage: llama config cache <type>"; return 1; }
            export LLM_DEFAULT_CACHE_TYPE_K="$value"
            export LLM_DEFAULT_CACHE_TYPE_V="$value"
            echo "✓ LLM_DEFAULT_CACHE_TYPE_K=$LLM_DEFAULT_CACHE_TYPE_K"
            echo "✓ LLM_DEFAULT_CACHE_TYPE_V=$LLM_DEFAULT_CACHE_TYPE_V"
            ;;
        pipe-n)
            if [[ "$value" =~ ^[0-9]+$ ]]; then
                export LLM_PIPE_N_PREDICT="$value"
                echo "✓ LLM_PIPE_N_PREDICT=$LLM_PIPE_N_PREDICT"
            else
                echo "Usage: llama config pipe-n <n>"
                return 1
            fi
            ;;
        no-thinking)
            case "$value" in
                on|1|true|yes)
                    export LLM_NO_THINKING="1"
                    echo "✓ LLM_NO_THINKING=$LLM_NO_THINKING"
                    ;;
                off|0|false|no|"")
                    export LLM_NO_THINKING="0"
                    echo "✓ LLM_NO_THINKING=$LLM_NO_THINKING"
                    ;;
                *)
                    echo "Usage: llama config no-thinking <on|off>"
                    return 1
                    ;;
            esac
            ;;
        save)
            local out_file="${value:-$LLM_RUNTIME_CONFIG_FILE}"
            mkdir -p "$(dirname "$out_file")"
            cat > "$out_file" <<EOF
# Generated by llama config save
export LLM_DEFAULT_CACHE_TYPE_K="${LLM_DEFAULT_CACHE_TYPE_K}"
export LLM_DEFAULT_CACHE_TYPE_V="${LLM_DEFAULT_CACHE_TYPE_V}"
export LLM_DEFAULT_CTX="${LLM_DEFAULT_CTX}"
export LLM_DEFAULT_THREADS="${LLM_DEFAULT_THREADS}"
export LLM_PIPE_N_PREDICT="${LLM_PIPE_N_PREDICT}"
export LLM_NO_THINKING="${LLM_NO_THINKING}"
EOF
            echo "✓ Saved runtime config to: $out_file"
            if [ "$out_file" = "$LLM_RUNTIME_CONFIG_FILE" ]; then
                echo "  This file is auto-loaded when llama-aliases.sh is sourced."
            else
                echo "  Load this custom file with: llama config load \"$out_file\""
            fi
            ;;
        load)
            local in_file="${value:-$LLM_RUNTIME_CONFIG_FILE}"
            if [ ! -f "$in_file" ]; then
                echo "Config file not found: $in_file"
                return 1
            fi
            # shellcheck disable=SC1090
            source "$in_file"
            echo "✓ Loaded runtime config from: $in_file"
            echo "  Run 'llama config show' to verify"
            ;;
        *)
            echo "Unknown config key: $key"
            echo "Run: llama config show"
            return 1
            ;;
    esac
}
