#!/usr/bin/env bash
# llama-env.sh — Environment variables and constants

LLM_MODELS_DIR="${LLM_MODELS_DIR:-$HOME/.llama/llama-models}"
LLM_DEFAULT_CTX="${LLM_DEFAULT_CTX:-32768}"
LLM_DEFAULT_GPU_LAYERS="${LLM_DEFAULT_GPU_LAYERS:-99}"
LLM_SERVER_HOST="${LLM_SERVER_HOST:-127.0.0.1}"
LLM_SERVER_PORT="${LLM_SERVER_PORT:-11434}"
LLM_HF_DEFAULT_USER="${LLM_HF_DEFAULT_USER:-unsloth}"
LLM_DEFAULT_CACHE_TYPE_K="${LLM_DEFAULT_CACHE_TYPE_K:-f16}"
LLM_DEFAULT_CACHE_TYPE_V="${LLM_DEFAULT_CACHE_TYPE_V:-f16}"
LLM_RUNTIME_CONFIG_FILE="${LLM_RUNTIME_CONFIG_FILE:-$HOME/.llama/llama-runtime.env}"
LLM_DEFAULT_THREADS="${LLM_DEFAULT_THREADS:-}"
LLM_PIPE_N_PREDICT="${LLM_PIPE_N_PREDICT:-4096}"
LLM_NO_THINKING="${LLM_NO_THINKING:-0}"

_LLAMA_MTP_DRAFT_N_MAX=2
_LLAMA_MLX_CHAT_MODULE="mlx_vlm.chat"
_LLAMA_MODEL_INDEX_FILE="$LLM_MODELS_DIR/.llama-model-index.json"

_llama_resolve_cache_type_k() { echo "$LLM_DEFAULT_CACHE_TYPE_K"; }
_llama_resolve_cache_type_v() { echo "$LLM_DEFAULT_CACHE_TYPE_V"; }

if [[ -n "$LLM_RUNTIME_CONFIG_FILE" && -f "$LLM_RUNTIME_CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$LLM_RUNTIME_CONFIG_FILE"
fi
